# fly.toml file generated for restoreb on 2023-02-12T14:09:51-05:00

app = "restoreb"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "byrnesbyrnes/restore:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51MVdPqJ97kqFDFqpwjvIJqlHx4kGcjU2r8j9n4i58FngVF6kfSWGK51LSMaQOO7XGkTpxwlCInQksStrgNu4rsnG004Rb5kv28"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
